
project_id = "pqxzzviqodstimvybgow"

[functions.fetch-events]
verify_jwt = false

[functions.process-notifications]
verify_jwt = false

[functions.execute-trade]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.webhook-stripe]
verify_jwt = false
