// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbtghjsbmlrxdmgqixfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFidGdoanNibWxyeGRtZ3FpeGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MTU3MDAsImV4cCI6MjA1MjE5MTcwMH0.JFnTNoftsMSNBn0m1Zu9vlq_p8aGQnqYYym1cT0p3So";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);